name: Notify Members of Convention Change

on:
  pull_request_target:
    paths:
      - docs/Coding-Conventions.md

jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'ni'
    runs-on: ubuntu-20.04
    steps:
      - name: Noop
        run: "true"
  notify:
    runs-on: ubuntu-latest
    needs: org-check
    steps:
      - uses: actions/checkout@master
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: Notify-Convention-Change.md
